# https://pre-commit.com/
repos:
  # using custom command in pre-commit
  # https://stackoverflow.com/questions/59499061/how-to-run-custom-shell-script-file-before-pre-commit-hook
  # code formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      # - id: check-json
      #   exclude: ^(.vscode/|other/folder/) # weird errors with .vscode/*.json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^((.*)\.(ipynb|otherext)) # avoid reformat notebooks everytime
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: ^((.*)\.(html))
  # - repo: https://github.com/myint/rstcheck
  #   rev: 3f92957478422df87bd730abde66f089cc1ee19b
  #   hooks:
  #     - id: rstcheck
  #       args: [
  #           # "--report",
  #           # "info",
  #           "--ignore-directives",
  #           "autofunction,automodule,bibliography,math,numfig,plot,testcode,testoutput",
  #           "--ignore-roles",
  #           "eq,cite",
  #         ]
  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.13
  #   hooks:
  #     - id: mdformat
  #       additional_dependencies:
  #       - mdformat-gfm
  #       - mdformat-black
  # push up-to-date documentation after every commit
  # https://stackoverflow.com/questions/59499061/how-to-run-custom-shell-script-file-before-pre-commit-hook
  # - repo: local
  #   hooks:
  #   - id: doc
  #     name: doc
  #     entry: bash -c 'make -C docs/ html'
  #     # entry: bash -c ';'
  #     verbose: true
  #     language: python
# git commit -m "Build documentation as of $(git log '--format=format:%H' master -1)"
# git push origin `git subtree split --prefix docs/build/html master`:gh-pages
